import {
	analyticsConfig,
	announcementConfig,
	backgroundWallpaper,
	booknavConfig,
	booknavPageConfig,
	commentConfig,
	coverImageConfig,
	displaySettingsConfig,
	dynamicConfig,
	expressiveCodeConfig,
	fontConfig,
	fontsList,
	footerConfig,
	friendsPageConfig,
	galleryConfig,
	licenseConfig,
	live2dWidgetConfig,
	mermaidConfig,
	musicPlayerConfig,
	navBarConfig,
	navBarSearchConfig,
	plantumlConfig,
	profileConfig,
	sakuraConfig,
	sidebarLayoutConfig,
	siteConfig,
	spineModelConfig,
	sponsorConfig,
} from "../src/config/index";
import { friendsConfig } from "../src/config/friendsConfig";
import { LinkPresets } from "../src/config/navBarConfig";

const modules = {
	siteConfig,
	profileConfig,
	announcementConfig,
	backgroundWallpaper,
	coverImageConfig,
	displaySettingsConfig,
	sidebarLayoutConfig,
	sakuraConfig,
	fontConfig,
	fontsList,
	expressiveCodeConfig,
	commentConfig,
	analyticsConfig,
	musicPlayerConfig,
	dynamicConfig,
	friendsPageConfig,
	friendsConfig,
	galleryConfig,
	booknavPageConfig,
	booknavConfig,
	sponsorConfig,
	footerConfig,
	licenseConfig,
	navBarConfig,
	LinkPresets,
	navBarSearchConfig,
	mermaidConfig,
	plantumlConfig,
	spineModelConfig,
	live2dWidgetConfig,
};

process.stdout.write(JSON.stringify(modules));
